package com.soliano.betvalueanalyzer.ui.components

import com.soliano.betvalueanalyzer.data.local.PredictionEntity

data class SportPredictionCopy(
    val topLabel: String,
    val contextLine: String,
    val cardLabel: String,
    val readingTitle: String,
    val probabilityMetricLabel: String,
    val probabilityMeaning: String,
    val expectedHeader: String,
    val expectedShortLabel: String,
    val expectedProbabilityLabel: String,
    val statsTitle: String,
    val scenariosTitle: String,
    val lineupTitle: String,
    val playerTitle: String,
    val playerFooter: String,
)

fun sportPredictionCopy(sportKey: String, sportTitle: String): SportPredictionCopy {
    return when (baseSport(sportKey)) {
        "soccer" -> SportPredictionCopy(
            topLabel = "PRONOSTIC LE PLUS ROBUSTE À 90 MINUTES",
            contextLine = "Hors prolongations et tirs au but",
            cardLabel = "PRONOSTIC À 90 MINUTES",
            readingTitle = "Lecture football à 90 minutes",
            probabilityMetricLabel = "Chance du pronostic",
            probabilityMeaning = "chance estimée que le pronostic se produise à la fin du temps réglementaire",
            expectedHeader = "SCORE FINAL PROBABLE SI CE PRONOSTIC SE RÉALISE",
            expectedShortLabel = "Score probable",
            expectedProbabilityLabel = "parmi ces scores",
            statsTitle = "Statistiques football récentes",
            scenariosTitle = "Probabilités football : résultat, buts, tirs et corners",
            lineupTitle = "Compositions des équipes",
            playerTitle = "Buteurs et passeurs probables",
            playerFooter = "Buts et passes décisives uniquement, pour titulaires et remplaçants probables quand les données existent.",
        )
        "rugby" -> SportPredictionCopy(
            topLabel = "ISSUE LA PLUS ROBUSTE AU TEMPS RÉGLEMENTAIRE",
            contextLine = "Vainqueur, total points, essais, transformations, pénalités, touches, mêlées et discipline",
            cardLabel = "LECTURE RUGBY",
            readingTitle = "Lecture rugby",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue rugby se produise selon les données disponibles",
            expectedHeader = "SCORE PROJETÉ AU TEMPS RÉGLEMENTAIRE",
            expectedShortLabel = "Score projeté",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques rugby récentes",
            scenariosTitle = "Probabilités rugby : vainqueur, points, essais, pénalités, transformations, touches et mêlées",
            lineupTitle = "Compositions / groupes rugby",
            playerTitle = "Joueurs rugby à surveiller",
            playerFooter = "Quand les données existent : essais, buteurs, pénalités/transformations, plaquages, charge récente et rôle titulaire/remplaçant.",
        )
        "basketball" -> SportPredictionCopy(
            topLabel = "PRONOSTIC MATCH COMPLET",
            contextLine = "Vainqueur, total de points, rythme, rotations et joueurs",
            cardLabel = "LECTURE BASKET",
            readingTitle = "Lecture basketball",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue basket se produise sur le match",
            expectedHeader = "SCORE PROJETÉ DU MATCH",
            expectedShortLabel = "Score projeté",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques basket récentes",
            scenariosTitle = "Probabilités basket : vainqueur et total de points",
            lineupTitle = "Cinq majeur / rotations",
            playerTitle = "Scénarios joueurs basket",
            playerFooter = "Points, rebonds et passes joueurs quand les boxscores publics sont exploitables.",
        )
        "baseball" -> SportPredictionCopy(
            topLabel = "PRONOSTIC BASEBALL",
            contextLine = "Vainqueur, runs, lanceurs probables, bullpen et forme offensive",
            cardLabel = "LECTURE BASEBALL",
            readingTitle = "Lecture baseball",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue baseball se produise sur le match",
            expectedHeader = "SCORE PROJETÉ EN RUNS",
            expectedShortLabel = "Runs projetés",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques baseball récentes",
            scenariosTitle = "Probabilités baseball : vainqueur et total de runs",
            lineupTitle = "Lineups / lanceurs probables",
            playerTitle = "Scénarios joueurs baseball",
            playerFooter = "Coups sûrs et home runs quand les statistiques joueurs sont disponibles.",
        )
        "hockey" -> SportPredictionCopy(
            topLabel = "PRONOSTIC HOCKEY SUR GLACE",
            contextLine = "Vainqueur, buts, gardiens, tirs, power play et absences",
            cardLabel = "LECTURE HOCKEY",
            readingTitle = "Lecture hockey sur glace",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue hockey se produise selon le marché suivi",
            expectedHeader = "SCORE PROJETÉ EN BUTS",
            expectedShortLabel = "Score projeté",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques hockey sur glace récentes",
            scenariosTitle = "Probabilités hockey : vainqueur, total de buts, gardiens et power play",
            lineupTitle = "Alignements / gardiens",
            playerTitle = "Joueurs hockey à surveiller",
            playerFooter = "Buts et assists si les données joueurs sont disponibles.",
        )
        "field_hockey" -> SportPredictionCopy(
            topLabel = "PRONOSTIC HOCKEY SUR GAZON",
            contextLine = "Vainqueur, buts, penalty corners, gardiens, cartons et forme",
            cardLabel = "LECTURE HOCKEY GAZON",
            readingTitle = "Lecture hockey sur gazon",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue hockey sur gazon se produise",
            expectedHeader = "SCORE PROJETÉ EN BUTS",
            expectedShortLabel = "Score projeté",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques hockey sur gazon récentes",
            scenariosTitle = "Probabilités hockey gazon : vainqueur, buts, penalty corners et discipline",
            lineupTitle = "Effectifs / gardiens",
            playerTitle = "Joueurs hockey gazon à surveiller",
            playerFooter = "Buts et penalty corners seulement si les données publiques sont exploitables.",
        )
        "football" -> SportPredictionCopy(
            topLabel = "PRONOSTIC FOOTBALL AMÉRICAIN",
            contextLine = "Vainqueur, points, handicap, quarterback, touchdowns et turnovers",
            cardLabel = "LECTURE FOOT US",
            readingTitle = "Lecture football américain",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue football américain se produise",
            expectedHeader = "SCORE PROJETÉ EN POINTS",
            expectedShortLabel = "Score projeté",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques football américain récentes",
            scenariosTitle = "Probabilités football US : vainqueur, total points, handicap et touchdowns",
            lineupTitle = "Depth chart / titulaires",
            playerTitle = "Joueurs football US à surveiller",
            playerFooter = "Touchdowns, yards et points joueurs uniquement quand les données publiques sont assez solides.",
        )
        "australian_football" -> SportPredictionCopy(
            topLabel = "PRONOSTIC FOOTBALL AUSTRALIEN",
            contextLine = "Vainqueur, points, goals/behinds, marks, possessions et météo",
            cardLabel = "LECTURE AFL",
            readingTitle = "Lecture football australien",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue football australien se produise",
            expectedHeader = "SCORE PROJETÉ EN POINTS",
            expectedShortLabel = "Score projeté",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques football australien récentes",
            scenariosTitle = "Probabilités AFL : vainqueur, total points, goals et marks",
            lineupTitle = "Effectifs / rôles",
            playerTitle = "Joueurs AFL à surveiller",
            playerFooter = "Goals, possessions et marks seulement si les données publiques sont exploitables.",
        )
        "tennis" -> SportPredictionCopy(
            topLabel = "LECTURE TENNIS",
            contextLine = "Vainqueur, sets, surface, aces, service/retour, main gauche/droite, forme et fatigue du tableau",
            cardLabel = "LECTURE TENNIS",
            readingTitle = "Lecture tennis",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue tennis se produise sur le match",
            expectedHeader = "SCORE POSSIBLE EN SETS",
            expectedShortLabel = "Sets projetés",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques tennis récentes",
            scenariosTitle = "Probabilités tennis : vainqueur, sets, jeux, aces, breaks, tie-break et fatigue",
            lineupTitle = "Joueurs engagés",
            playerTitle = "Joueurs tennis",
            playerFooter = "Aces, breaks, jeux, surface, main gauche/droite et fatigue de match long sont pris en compte si les données publiques existent.",
        )
        "cycling" -> SportPredictionCopy(
            topLabel = "LECTURE COURSE CYCLISTE",
            contextLine = "Pas de buts ni de score : startlist, parcours, météo, favoris et rôles d’équipe",
            cardLabel = "SURVEILLANCE COURSE",
            readingTitle = "Lecture cyclisme",
            probabilityMetricLabel = "Niveau du signal",
            probabilityMeaning = "niveau de signal actuel ; ce n’est pas une probabilité de victoire tant que la startlist et les favoris ne sont pas consolidés",
            expectedHeader = "ÉTAT DE LA COURSE",
            expectedShortLabel = "État course",
            expectedProbabilityLabel = "fiabilité",
            statsTitle = "Données cyclisme disponibles",
            scenariosTitle = "Probabilités cyclisme : calendrier, startlist, podium/vainqueur si fiable",
            lineupTitle = "Équipes / coureurs engagés",
            playerTitle = "Coureurs à surveiller",
            playerFooter = "Vainqueur, podium ou top 10 seulement quand startlist, forme, parcours et météo sont recoupés.",
        )
        "racing" -> SportPredictionCopy(
            topLabel = "LECTURE FORMULE 1",
            contextLine = "Essais, qualifications, grille, pneus, rythme long run et météo",
            cardLabel = "MODÈLE F1",
            readingTitle = "Lecture Formule 1",
            probabilityMetricLabel = "Chance de victoire",
            probabilityMeaning = "chance estimée de victoire face à toute la grille",
            expectedHeader = "POSITION / GRILLE ATTENDUE",
            expectedShortLabel = "Projection course",
            expectedProbabilityLabel = "modèle grille",
            statsTitle = "Statistiques pilotes et écuries F1",
            scenariosTitle = "Probabilités F1 : vainqueur, podium, top 10 et duel pilote",
            lineupTitle = "Grille / écuries",
            playerTitle = "Pilotes F1 à surveiller",
            playerFooter = "Victoire, podium, top 10 et duel pilote quand essais, qualifications et rythme sont recoupés.",
        )
        "nascar" -> SportPredictionCopy(
            topLabel = "LECTURE NASCAR",
            contextLine = "Grille, rythme long run, pneus, track position, cautions et fiabilité",
            cardLabel = "MODÈLE NASCAR",
            readingTitle = "Lecture NASCAR",
            probabilityMetricLabel = "Chance de victoire",
            probabilityMeaning = "chance estimée de victoire face au peloton",
            expectedHeader = "POSITION / GRILLE ATTENDUE",
            expectedShortLabel = "Projection course",
            expectedProbabilityLabel = "modèle grille",
            statsTitle = "Statistiques pilotes NASCAR",
            scenariosTitle = "Probabilités NASCAR : vainqueur, top 5/top 10 et duel pilote",
            lineupTitle = "Grille / teams",
            playerTitle = "Pilotes NASCAR à surveiller",
            playerFooter = "Victoire, top 5/top 10 et duel pilote quand grille, rythme et cautions probables sont recoupés.",
        )
        "golf" -> SportPredictionCopy(
            topLabel = "LECTURE TOURNOI GOLF",
            contextLine = "Vainqueur, top 5/top 10, cut, forme et profil du parcours",
            cardLabel = "LECTURE GOLF",
            readingTitle = "Lecture golf",
            probabilityMetricLabel = "Niveau du signal",
            probabilityMeaning = "niveau de signal actuel pour le tournoi ; vainqueur/top 10 seulement si les données sont suffisantes",
            expectedHeader = "ÉTAT DU TOURNOI",
            expectedShortLabel = "Tournoi",
            expectedProbabilityLabel = "fiabilité",
            statsTitle = "Données golf disponibles",
            scenariosTitle = "Probabilités golf : vainqueur, top 10 et cut si fiable",
            lineupTitle = "Joueurs engagés",
            playerTitle = "Golfeurs à surveiller",
            playerFooter = "Top 10, cut ou vainqueur uniquement si forme récente et parcours sont recoupés.",
        )
        "mma" -> SportPredictionCopy(
            topLabel = "LECTURE MMA",
            contextLine = "Vainqueur, KO/TKO, soumission, décision, rounds, striking et grappling",
            cardLabel = "LECTURE MMA",
            readingTitle = "Lecture MMA",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue MMA se produise",
            expectedHeader = "SCÉNARIO MMA",
            expectedShortLabel = "Scénario",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques MMA disponibles",
            scenariosTitle = "Probabilités MMA : vainqueur, méthode, rounds et grappling",
            lineupTitle = "Combattants",
            playerTitle = "Combattants MMA à surveiller",
            playerFooter = "KO/TKO, soumission, décision et rounds seulement si les données publiques sont assez solides.",
        )
        "boxing" -> SportPredictionCopy(
            topLabel = "LECTURE BOXE",
            contextLine = "Vainqueur, KO/TKO, décision, rounds, reach, volume et cardio",
            cardLabel = "LECTURE BOXE",
            readingTitle = "Lecture boxe",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue boxe se produise",
            expectedHeader = "SCÉNARIO BOXE",
            expectedShortLabel = "Scénario",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques boxe disponibles",
            scenariosTitle = "Probabilités boxe : vainqueur, KO/TKO, décision et rounds",
            lineupTitle = "Boxeurs",
            playerTitle = "Boxeurs à surveiller",
            playerFooter = "KO/TKO, décision ou rounds seulement si reach, forme et historique sont assez solides.",
        )
        "cricket" -> SportPredictionCopy(
            topLabel = "LECTURE CRICKET",
            contextLine = "Vainqueur, runs, wickets, forme batteurs/lanceurs et météo",
            cardLabel = "LECTURE CRICKET",
            readingTitle = "Lecture cricket",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue cricket se produise",
            expectedHeader = "PROJECTION EN RUNS",
            expectedShortLabel = "Runs projetés",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques cricket récentes",
            scenariosTitle = "Probabilités cricket : vainqueur et total de runs",
            lineupTitle = "XI probables",
            playerTitle = "Batteurs/lanceurs à surveiller",
            playerFooter = "Runs, wickets et performances joueurs si les données existent.",
        )
        "handball" -> SportPredictionCopy(
            topLabel = "LECTURE HANDBALL",
            contextLine = "Vainqueur, buts, gardiens, exclusions 2 minutes, rythme et rotations",
            cardLabel = "LECTURE HANDBALL",
            readingTitle = "Lecture handball",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue handball se produise",
            expectedHeader = "SCORE PROJETÉ EN BUTS",
            expectedShortLabel = "Buts projetés",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques handball récentes",
            scenariosTitle = "Probabilités handball : vainqueur, total de buts, écart et gardiens",
            lineupTitle = "Effectifs / gardiens",
            playerTitle = "Joueurs handball à surveiller",
            playerFooter = "Buts et passes décisives seulement si les données publiques sont disponibles.",
        )
        "volleyball" -> SportPredictionCopy(
            topLabel = "LECTURE VOLLEY",
            contextLine = "Vainqueur, sets, dynamique de service/réception et forme récente",
            cardLabel = "LECTURE VOLLEY",
            readingTitle = "Lecture volley-ball",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue volley se produise",
            expectedHeader = "SCORE PROJETÉ EN SETS",
            expectedShortLabel = "Sets projetés",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques volley récentes",
            scenariosTitle = "Probabilités volley : vainqueur et sets",
            lineupTitle = "Six de départ / effectifs",
            playerTitle = "Joueurs volley à surveiller",
            playerFooter = "Points, aces ou blocs seulement si les données publiques existent.",
        )
        "athletics" -> SportPredictionCopy(
            topLabel = "LECTURE ATHLÉTISME",
            contextLine = "Startlist, records saison, qualification, finale, couloir et météo",
            cardLabel = "LECTURE ATHLÉTISME",
            readingTitle = "Lecture athlétisme",
            probabilityMetricLabel = "Niveau du signal",
            probabilityMeaning = "niveau de signal actuel pour l’épreuve ; podium/qualification seulement si la startlist et les records récents sont solides",
            expectedHeader = "ÉTAT DE L’ÉPREUVE",
            expectedShortLabel = "Épreuve",
            expectedProbabilityLabel = "fiabilité",
            statsTitle = "Données athlétisme disponibles",
            scenariosTitle = "Probabilités athlétisme : qualification, podium et duel si fiable",
            lineupTitle = "Athlètes engagés",
            playerTitle = "Athlètes à surveiller",
            playerFooter = "Médaille, qualification ou duel uniquement avec startlist, records saison et contexte météo.",
        )
        "darts" -> SportPredictionCopy(
            topLabel = "LECTURE FLÉCHETTES",
            contextLine = "Vainqueur, moyenne 3 fléchettes, checkout, format legs/sets et ranking",
            cardLabel = "LECTURE FLÉCHETTES",
            readingTitle = "Lecture fléchettes",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue fléchettes se produise",
            expectedHeader = "SCÉNARIO EN LEGS / SETS",
            expectedShortLabel = "Format projeté",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques fléchettes disponibles",
            scenariosTitle = "Probabilités fléchettes : vainqueur, handicap legs/sets et checkout",
            lineupTitle = "Joueurs",
            playerTitle = "Joueurs à surveiller",
            playerFooter = "Moyenne, checkout et 180 seulement quand les données publiques sont assez solides.",
        )
        "snooker" -> SportPredictionCopy(
            topLabel = "LECTURE SNOOKER",
            contextLine = "Vainqueur, frames, centuries, ranking, forme et format",
            cardLabel = "LECTURE SNOOKER",
            readingTitle = "Lecture snooker",
            probabilityMetricLabel = "Chance de l’issue",
            probabilityMeaning = "chance estimée que cette issue snooker se produise",
            expectedHeader = "SCÉNARIO EN FRAMES",
            expectedShortLabel = "Frames projetées",
            expectedProbabilityLabel = "projection",
            statsTitle = "Statistiques snooker disponibles",
            scenariosTitle = "Probabilités snooker : vainqueur, handicap frames et centuries",
            lineupTitle = "Joueurs",
            playerTitle = "Joueurs à surveiller",
            playerFooter = "Centuries, frames et handicap seulement si ranking et forme récente sont recoupés.",
        )
        else -> genericTeamCopy(sportTitle.ifBlank { "sport" }, "points", sportTitle.ifBlank { "Sport" })
    }
}

fun probabilityMeaningSentence(prediction: PredictionEntity, copy: SportPredictionCopy): String {
    if (prediction.category.startsWith("Données")) {
        return cleanDisplayText(
            "${formatPercent(prediction.consensusProbability)} est un niveau neutre de référence : ce n’est pas une probabilité de victoire tant que les données propres au sport ne sont pas assez solides."
        )
    }
    return cleanDisplayText(
        "${formatPercent(prediction.consensusProbability)} représente ${copy.probabilityMeaning} pour « ${prediction.selection} »."
    )
}

private fun genericTeamCopy(@Suppress("UNUSED_PARAMETER") key: String, unit: String, title: String): SportPredictionCopy = SportPredictionCopy(
    topLabel = "LECTURE ${title.uppercase()}",
    contextLine = "Vainqueur, total de $unit, forme récente et absences",
    cardLabel = "LECTURE ${title.uppercase()}",
    readingTitle = "Lecture $title",
    probabilityMetricLabel = "Chance de l’issue",
    probabilityMeaning = "chance estimée que cette issue se produise",
    expectedHeader = "PROJECTION EN ${unit.uppercase()}",
    expectedShortLabel = "Projection",
    expectedProbabilityLabel = "projection",
    statsTitle = "Statistiques $title récentes",
    scenariosTitle = "Probabilités $title : vainqueur et total de $unit",
    lineupTitle = "Effectifs / compositions",
    playerTitle = "Joueurs à surveiller",
    playerFooter = "Performances joueurs affichées seulement quand les données publiques sont assez solides.",
)

private fun baseSport(sportKey: String): String = sportKey.substringBefore('/')
